# Generated by Django 5.1.1 on 2024-10-23 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_usuario_comentario_autor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
