# Generated by Django 5.1.1 on 2024-10-28 23:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_categoria_birth_date_comentario_birth_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.AddField(
            model_name='categoria',
            name='avatar',
            field=models.CharField(blank=True, default='avatar_1.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='avatar',
            field=models.CharField(blank=True, default='avatar_1.png', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.CharField(blank=True, default='avatar_1.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='avatar_1.png', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
