# Generated by Django 5.1.1 on 2024-11-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_categoria_birth_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cuerpo',
            new_name='descripcion',
        ),
    ]
