# Generated by Django 5.1.1 on 2024-11-01 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_cuerpo_post_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='post',
            name='fecha_publicacion',
        ),
        migrations.AlterField(
            model_name='post',
            name='categoria',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.categoria'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
    ]
